steps:
  #Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'builder_api_key=$_BUILDER_KEY',
        '-t',
        'gcr.io/sublime-lens-235221/github.com/pazano/danielle-portfolio:${SHORT_SHA}',
        '.',
      ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/sublime-lens-235221/github.com/pazano/danielle-portfolio:${SHORT_SHA}',
      ]
  # Deploy the container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'run',
        'deploy',
        '$_CLOUD_RUN_SERVICE',
        '--image',
        'gcr.io/sublime-lens-235221/github.com/pazano/danielle-portfolio:${SHORT_SHA}',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--max-instances',
        '2',
        '--allow-unauthenticated',
      ]
